export const styles = {
  container: {
    flex: 1,
    paddingTop: 32,
    paddingLeft: 16,
    paddingRight: 16,
    backgroundColor: "#FFF",
  },
  postContainer: {
    marginBottom: 34,
  },
  userInfo: {
    flexDirection: "row",
    marginBottom: 32,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#BDBDBD",
    marginRight: 8,
    overflow: "hidden",
  },
  avatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    borderRadius: 16,
  },
  username: {
    fontFamily: "Roboto - regular",
    fontWeight: 700,
    fontSize: 13,
    lineHeight: 15,
    color: "#212121",
  },
  email: {
    fontFamily: "Roboto - regular",
    fontSize: 11,
    lineHeight: 13,
    color: "rgba(33, 33, 33, 0.8)",
  },
  photo: {
    height: 240,
    width: "100%",
    borderRadius: 8,
    overflow: "hidden",
    objectFit: "cover",
    marginBottom: 8,
  },
  title: {
    fontFamily: "Roboto - medium",
    fontSize: 16,
    lineHeight: 19,
    color: "#212121",
    marginBottom: 11,
  },
  place: {
    fontFamily: "Roboto - regular",
    fontSize: 16,
    lineHeight: 19,
    color: "#212121",
    textDecorationLine: "underline",
  },
  count: {
    fontFamily: "Roboto - regular",
    fontSize: 16,
    lineHeight: 19,
    color: "#212121",
  },
};
